name: Windows
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'script.js'
      - 'gen_tw_ts.py'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'script.js'
      - 'gen_tw_ts.py'
jobs:
  build:
    name: Build
    # 运行平台， windows-latest 目前是 windows server 2019
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        qt_ver: [5.15.0]
        # mingw 用不了
        # qt_arch: [win64_msvc2017_64, win32_msvc2017, win32_mingw53,win32_mingw73]
        qt_arch: [win64_msvc2019_64, win32_msvc2019]
        qt_target: [desktop]
        # 额外设置 msvc_arch
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
          - qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
    env:
      targetName: diserver.exe
    # 步骤
    steps:
      - name: cacheQt
        id: WindowsCacheQt
        uses: actions/cache@v2
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch_install}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
      - name: setupQt
        if: steps.WindowsCacheQt.outputs.cache-hit == 'true'
        shell: pwsh
        env:
          QtPath: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch_install}}
        run: |
          $qt_Path=${env:QtPath}
          echo "::set-env name=Qt5_Dir::$qt_Path"
          echo "::add-path::$qt_Path/bin"
      # 安装 Qt
      - name: Install Qt
        if: steps.WindowsCacheQt.outputs.cache-hit != 'true'
        # 使用外部 action。这个 action 专门用来安装Qt
        uses: jurplel/install-qt-action@v2
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
          cached: ${{ steps.WindowsCacheQt.outputs.cache-hit }}
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # 编译 msvc
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          cd server
          qmake CONFIG+=release
          nmake
          cd ..
      # tag 打包
      - name: package
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
          archiveName: ${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
        shell: pwsh
        run: |
          # 创建文件夹
          New-Item -ItemType Directory ${env:archiveName}
          # 拷贝 exe
          Copy-Item server\release\${env:targetName} ${env:archiveName}\
          # 拷贝依赖
          windeployqt --qmldir . ${env:archiveName}\${env:targetName}
          Remove-Item -Recurse -Force ${env:archiveName}\bearer, ${env:archiveName}\iconengines, ${env:archiveName}\imageformats, ${env:archiveName}\translations
          Remove-Item -Force ${env:archiveName}\D3Dcompiler_47.dll, ${env:archiveName}\libEGL.dll, ${env:archiveName}\libGLESv2.dll, ${env:archiveName}\opengl32sw.dll
          if (Test-Path ${env:archiveName}\vc_redist.x64.exe) {
            echo "::set-env name=vcRedistFile::vc_redist.x64.exe"
          } else {
            echo "::set-env name=vcRedistFile::vc_redist.x86.exe"
          }
          Move-Item -Force -Path ${env:archiveName}\${env:vcRedistFile} -Destination .
          # 打包 zip
          Compress-Archive -Path ${env:archiveName} ${env:archiveName}'.zip'
          # 记录环境变量 packageName 给后续 step
          $name = ${env:archiveName}
          echo "::set-env name=packageName::$name"
          # 打印环境变量 packageName
          Write-Host 'packageName:'${env:packageName}
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.packageName }}.zip
          asset_name: ${{ env.packageName }}.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: uploadRelease_vc_redist
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.vcRedistFile }}
          asset_name: ${{ env.vcRedistFile }}
          tag: ${{ github.ref }}
          overwrite: true
